const express = require('express');
const router = express.Router();
const auth = require('../../middleware/auth');

// @route   GET api/reports
// @desc    Get all reports
// @access  Private
router.get('/', auth, async (req, res) => {
  try {
    // Mock report data - in a real implementation, this would query from a database
    const mockReports = [];
    
    const reportTypes = [
      'Security Incident Summary', 
      'Network Traffic Analysis', 
      'System Performance Report',
      'User Activity Audit',
      'Compliance Report',
      'Threat Intelligence Briefing'
    ];
    
    // Generate mock reports
    for (let i = 0; i < 50; i++) {
      const typeIndex = Math.floor(Math.random() * reportTypes.length);
      const createdAt = new Date(Date.now() - Math.floor(Math.random() * 90 * 24 * 60 * 60 * 1000)); // Within last 90 days
      
      mockReports.push({
        id: `report-${i}`,
        name: `${reportTypes[typeIndex]} - ${createdAt.toISOString().split('T')[0]}`,
        type: reportTypes[typeIndex],
        description: `Automated report generated by Logware for ${reportTypes[typeIndex]}`,
        createdAt,
        createdBy: `user-${Math.floor(Math.random() * 10)}`,
        lastViewed: Math.random() > 0.5 ? new Date(createdAt.getTime() + Math.floor(Math.random() * (Date.now() - createdAt.getTime()))) : null,
        format: Math.random() > 0.3 ? 'PDF' : 'CSV',
        size: `${Math.floor(Math.random() * 900) + 100}KB`,
        status: 'completed'
      });
    }
    
    // Sort by creation date (newest first)
    mockReports.sort((a, b) => b.createdAt - a.createdAt);
    
    res.json(mockReports);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET api/reports/:id
// @desc    Get report by ID
// @access  Private
router.get('/:id', auth, async (req, res) => {
  try {
    const reportId = req.params.id;
    
    // In a real implementation, this would fetch from a database
    // For now, generate a mock report based on the ID
    
    const idNumber = parseInt(reportId.replace('report-', '')) || 0;
    const reportTypes = [
      'Security Incident Summary', 
      'Network Traffic Analysis', 
      'System Performance Report',
      'User Activity Audit',
      'Compliance Report',
      'Threat Intelligence Briefing'
    ];
    
    const typeIndex = idNumber % reportTypes.length;
    const createdAt = new Date(Date.now() - (idNumber * 86400000)); // Each ID is one day older
    
    const report = {
      id: reportId,
      name: `${reportTypes[typeIndex]} - ${createdAt.toISOString().split('T')[0]}`,
      type: reportTypes[typeIndex],
      description: `Comprehensive ${reportTypes[typeIndex]} generated by Logware`,
      createdAt,
      createdBy: `user-${idNumber % 10}`,
      lastViewed: Math.random() > 0.5 ? new Date(createdAt.getTime() + 3600000) : null,
      format: 'PDF',
      size: `${Math.floor(Math.random() * 900) + 100}KB`,
      status: 'completed',
      data: {
        summary: {
          totalEvents: 1000 + (idNumber * 100),
          criticalEvents: 5 + (idNumber % 10),
          timeSpan: '24 hours',
          topSources: [
            { name: 'Snort', count: 350 + (idNumber % 100) },
            { name: 'OSSIM', count: 280 + (idNumber % 100) },
            { name: 'Nagios', count: 220 + (idNumber % 100) },
            { name: 'Zeek', count: 150 + (idNumber % 100) }
          ]
        },
        insights: [
          'Increase in SSH brute force attempts from Eastern European IPs',
          'Unusual outbound traffic pattern detected to port 8080',
          'Database servers showing higher than normal CPU utilization',
          'Multiple failed login attempts for admin accounts'
        ],
        recommendations: [
          'Update firewall rules to block suspicious IPs',
          'Implement additional authentication controls for admin accounts',
          'Schedule server maintenance to address resource utilization',
          'Enable enhanced logging for database transactions'
        ],
        charts: [
          {
            type: 'bar',
            title: 'Events by Severity',
            data: {
              labels: ['Critical', 'High', 'Medium', 'Low'],
              values: [5 + (idNumber % 10), 25 + (idNumber % 30), 120 + (idNumber % 100), 850 + (idNumber % 200)]
            }
          },
          {
            type: 'line',
            title: 'Events Over Time',
            data: {
              labels: Array.from({ length: 24 }, (_, i) => `${i}:00`),
              values: Array.from({ length: 24 }, () => Math.floor(Math.random() * 100) + 20)
            }
          },
          {
            type: 'pie',
            title: 'Events by Source',
            data: {
              labels: ['Snort', 'OSSIM', 'Nagios', 'Zeek', 'Other'],
              values: [35, 28, 22, 15, 10]
            }
          }
        ]
      }
    };
    
    res.json(report);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   POST api/reports
// @desc    Generate a new report
// @access  Private
router.post('/', auth, async (req, res) => {
  try {
    const { name, type, description, parameters } = req.body;
    
    if (!name || !type) {
      return res.status(400).json({ message: 'Name and type are required' });
    }
    
    // In a real implementation, this would create a report generation job
    // For now, just return a success response with a mock report ID
    
    const newReportId = `report-${Date.now()}`;
    
    res.json({
      id: newReportId,
      name,
      type,
      description,
      parameters,
      status: 'pending',
      createdAt: new Date(),
      createdBy: req.user.id,
      message: 'Report generation started'
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   POST api/reports/schedule
// @desc    Schedule a recurring report
// @access  Private
router.post('/schedule', auth, async (req, res) => {
  try {
    const { name, type, description, schedule, parameters, recipients } = req.body;
    
    if (!name || !type || !schedule) {
      return res.status(400).json({ message: 'Name, type, and schedule are required' });
    }
    
    // In a real implementation, this would create a scheduled report job
    // For now, just return a success response with a mock schedule ID
    
    const newScheduleId = `schedule-${Date.now()}`;
    
    res.json({
      id: newScheduleId,
      name,
      type,
      description,
      schedule,
      parameters,
      recipients,
      createdAt: new Date(),
      createdBy: req.user.id,
      nextRun: getNextRunDate(schedule),
      status: 'active',
      message: 'Report scheduled successfully'
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// Helper function to calculate next run date based on schedule
function getNextRunDate(schedule) {
  // This is a simplified implementation
  // In a real system, this would handle various schedule types (daily, weekly, monthly, etc.)
  const now = new Date();
  const nextRun = new Date(now);
  
  if (schedule.type === 'daily') {
    nextRun.setDate(now.getDate() + 1);
    nextRun.setHours(schedule.hour || 0, schedule.minute || 0, 0, 0);
  } else if (schedule.type === 'weekly') {
    const daysToAdd = (schedule.dayOfWeek - now.getDay() + 7) % 7;
    nextRun.setDate(now.getDate() + daysToAdd);
    nextRun.setHours(schedule.hour || 0, schedule.minute || 0, 0, 0);
  } else if (schedule.type === 'monthly') {
    nextRun.setMonth(now.getMonth() + 1);
    nextRun.setDate(schedule.dayOfMonth || 1);
    nextRun.setHours(schedule.hour || 0, schedule.minute || 0, 0, 0);
  }
  
  return nextRun;
}

module.exports = router;
